from functools import cache

from cachetools import cached
from cachetools.keys import hashkey

from ..actions.action_types import BonusAction
from ..battle_map import Map, map_toggled_cache_with_key
from ..misc import Conditions
from ..spells.spell import SpellStats
from ..effects.effect import Effect
from ..actions.actoid import Actoid, ActoidFlags
from ..threat_interfaces import ThreatModifierFactory, AttackThreatModifier
from itertools import combinations

class BlessFactory(ThreatModifierFactory):
    level = 1
    range = SpellStats.Range.FEET_30.value
    target = SpellStats.Target.THREE_CREATURES
    duration = SpellStats.Duration.MINUTE
    concentration = True
    type = SpellStats.Type.BUFF
    dc = None
    dmg_type = None

    def __init__(self, action_type, caster):
        self.action_type = action_type  # QUICKENED_BLESS, BLESS
        self.combatant = caster

    def __str__(self):
        """
        Important for FSM building
        """
        return "BlessFactory"


    def get_ability_name(self):
        return "Bless"


    def get_eligible_targets(self):
        swallower = self.combatant.get_swallower()
        if swallower:
            return [self.combatant]
        return combinations([a for a in Map.get().get_allies_within_radius(self.combatant, BlessFactory.range) if not a.is_affected_by(Conditions.SWALLOWED)], 3)

    def create_all(self):
        targets = self.get_eligible_targets()
        return [Bless(t, self) for t in targets]

    def calculate_threat_to_target(self, target, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        return 0

    def calculate_max_threat(self):
        targets = Map.get().get_enemies(self.combatant)
        return max([self.calculate_threat_to_target(t) for t in targets])


class Bless(Actoid, Effect, AttackThreatModifier):
    def __init__(self, targets, factory):
        super().__init__(ActoidFlags.IS_SPELL)
        self.targets = targets
        self.factory = factory


    def shorthand_str(self):
        return ("Quickened " if self.factory.action_type is BonusAction.QUICKENED_BLESS else "") + f"Bless"

    def activate(self):
        # todo should check if not already under the influence of another bless
        self.factory.combatant.concentration_effect = self
        for target in self.targets:
            for mod in target.saving_throws_dice_mod.values():
                mod.append('1d4')
            target.to_hit_dice_mod.append('1d4')

    def deactivate(self):
        self.factory.combatant.break_concentration()
        for target in self.targets:
            for mod in target.saving_throws_dice_mod.values():
                mod.remove('1d4')
            target.to_hit_dice_mod.remove('1d4')

    def is_affecting(self, combatant):
        return combatant in self.targets

    def calculate_threat(self, **kwargs):
        # TODO Multiply the threat increment by 3 for 3 rounds
        # TODO iterate over all abilities of the targets and try plugging the mods into their factories
        return 0

    def calculate_threat_for_attack(self, combatant, attack, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return attack.calculate_threat_delta({"to_hit_die": '1d4'})

    #@map_toggled_cache_with_key(key=lambda self, distances, shortest_paths: hashkey(self.factory.name, tuple(Map.get().get_combatant_position(self.factory.combatant).get()[0])))
    def get_eligible_coords(self, distances, shortest_paths):
        battle_map = Map.get()
        if not self.factory.combatant.is_affected_by_any(Conditions.GRAPPLED, Conditions.GRAPPLING, Conditions.RESTRAINED):
            coords_for_first = set(battle_map.get_free_coords_in_cartesian_range(battle_map.get_combatant_position(self.targets[0]),
                                                                            distances,
                                                                            inflate_to_size=self.factory.combatant.size,
                                                                            rng=BlessFactory.range,
                                                                            combatant=self.factory.combatant))
            coords_for_second = set(battle_map.get_free_coords_in_cartesian_range(battle_map.get_combatant_position(self.targets[1]),
                                                                              distances,
                                                                              inflate_to_size=self.factory.combatant.size,
                                                                              rng=BlessFactory.range,
                                                                              combatant=self.factory.combatant))
            coords_for_third = set(battle_map.get_free_coords_in_cartesian_range(battle_map.get_combatant_position(self.targets[2]),
                                                                              distances,
                                                                              inflate_to_size=self.factory.combatant.size,
                                                                              rng=BlessFactory.range,
                                                                              combatant=self.factory.combatant))
            return list(coords_for_third.intersection(coords_for_first.intersection(coords_for_second)))  # Strangely no visibility required
        elif battle_map.get_cartesian_distance_combatants(self.factory.combatant, self.targets[0]) <= BlessFactory.range \
            and battle_map.get_cartesian_distance_combatants(self.factory.combatant, self.targets[1]) <= BlessFactory.range \
            and battle_map.get_cartesian_distance_combatants(self.factory.combatant, self.targets[2]) <= BlessFactory.range:
            return [tuple(battle_map.get_combatant_position(self.factory.combatant).get()[0])]
        return None
