from functools import cache

from simulator.actions.action_types import BonusAction
from simulator.combatant_coords import CombatantCoords
from simulator.misc import Conditions
from simulator.spells.spell import SpellStats
from simulator.effects.effect import Effect
from simulator.actions.actoid import Actoid, ActoidFlags
from simulator.threat_interfaces import ThreatModifier, ThreatModifierFactory, AttackThreatModifier
from itertools import combinations


class BlessFactory(ThreatModifierFactory):
    level = 1
    range = SpellStats.Range.FEET_30.value
    target = SpellStats.Target.THREE_CREATURES
    duration = SpellStats.Duration.MINUTE
    concentration = True
    type = SpellStats.Type.BUFF
    dc = None
    dmg_type = None

    def __init__(self, action_type, caster, effect_tracker):
        self.action_type = action_type  # QUICKENED_BLESS, BLESS
        self.combatant = caster
        self.effect_tracker = effect_tracker

    def __str__(self):
        """
        Important for FSM building
        """
        return "BlessFactory"

    def get_eligible_targets(self, battle_map):
        return combinations([e for e in battle_map.get_enemies_within_radius(self.combatant, BlessFactory.range) if not e.is_affected_by(Conditions.SWALLOWED)], 3)

    def create_all(self, battle_map):
        targets = self.get_eligible_targets(battle_map)
        return [Bless(t, self) for t in targets]

    def calculate_threat_to_target(self, battle_map, target, *args, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        return 0

    def calculate_max_threat(self, battle_map):
        targets = battle_map.get_enemies(self.combatant)
        return max(targets, key=lambda t: self.calculate_threat_to_target(battle_map, t))


class Bless(Actoid, Effect, ThreatModifier, AttackThreatModifier):
    def __init__(self, targets, factory):
        super().__init__(ActoidFlags.IS_SPELL)
        self.targets = targets
        self.factory = factory


    def shorthand_str(self):
        return ("Quickened " if self.factory.action_type is BonusAction.QUICKENED_BLESS else "") + f"Bless"

    def activate(self, battle_map):
        # todo should check if not already under the influence of another bless
        self.factory.combatant.is_concentrating = True
        for target in self.targets:
            for mod in target.saving_throws_dice_mod.values():
                mod.append('1d')
            target.to_hit_dice_mod.append('1d4')

    def deactivate(self, battle_map):
        self.factory.combatant.is_concentrating = False
        for target in self.targets:
            for mod in target.saving_throws_dice_mod.values():
                mod.remove('1d')
            target.to_hit_dice_mod.remove('1d4')

    def is_affecting(self, combatant, battle_map):
        return combatant in self.targets


    def clear_cache(self):
        self.calculate_threat.cache_clear()

    @cache
    def calculate_threat(self, battle_map, *args, **kwargs):
        # TODO Multiply the threat increment by 3 for 3 rounds
        # TODO iterate over all abilities of the targets and try plugging the mods into their factories
        return 0

    def calculate_threat_for_attack(self, combatant, battle_map, attack, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return attack.calculate_threat_delta(battle_map, {"to_hit_die": '1d4'})
