from functools import cache

from simulator.actions.action_types import BonusAction
from simulator.battle_map import Map
from simulator.combatant_coords import CombatantCoords
from simulator.misc import Conditions
from simulator.spells.spell import SpellStats
from simulator.effects.effect import Effect
from simulator.actions.actoid import Actoid, ActoidFlags
from simulator.threat_interfaces import ThreatModifier, ThreatModifierFactory, AttackThreatModifier
from itertools import combinations


class BlessFactory(ThreatModifierFactory):
    level = 1
    range = SpellStats.Range.FEET_30.value
    target = SpellStats.Target.THREE_CREATURES
    duration = SpellStats.Duration.MINUTE
    concentration = True
    type = SpellStats.Type.BUFF
    dc = None
    dmg_type = None

    def __init__(self, action_type, caster):
        self.action_type = action_type  # QUICKENED_BLESS, BLESS
        self.combatant = caster

    def __str__(self):
        """
        Important for FSM building
        """
        return "BlessFactory"

    def get_eligible_targets(self):
        swallower = self.combatant.get_swallower()
        if swallower:
            return [self.combatant]
        return combinations([a for a in Map.get().get_allies_within_radius(self.combatant, BlessFactory.range) if not a.is_affected_by(Conditions.SWALLOWED)], 3)

    def create_all(self):
        targets = self.get_eligible_targets()
        return [Bless(t, self) for t in targets]

    def calculate_threat_to_target(self, target, *args, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        return 0

    def calculate_max_threat(self):
        targets = Map.get().get_enemies(self.combatant)
        return max(targets, key=lambda t: self.calculate_threat_to_target(t))


class Bless(Actoid, Effect, ThreatModifier, AttackThreatModifier):
    def __init__(self, targets, factory):
        super().__init__(ActoidFlags.IS_SPELL)
        self.targets = targets
        self.factory = factory


    def shorthand_str(self):
        return ("Quickened " if self.factory.action_type is BonusAction.QUICKENED_BLESS else "") + f"Bless"

    def activate(self):
        # todo should check if not already under the influence of another bless
        self.factory.combatant.concentration_effect = self
        for target in self.targets:
            for mod in target.saving_throws_dice_mod.values():
                mod.append('1d4')
            target.to_hit_dice_mod.append('1d4')

    def deactivate(self):
        self.factory.combatant.get_current_form().concentration_effect = None
        for target in self.targets:
            for mod in target.saving_throws_dice_mod.values():
                mod.remove('1d4')
            target.to_hit_dice_mod.remove('1d4')

    def is_affecting(self, combatant):
        return combatant in self.targets


    def calculate_threat(self, *args, **kwargs):
        # TODO Multiply the threat increment by 3 for 3 rounds
        # TODO iterate over all abilities of the targets and try plugging the mods into their factories
        return 0

    def calculate_threat_for_attack(self, combatant, attack, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return attack.calculate_threat_delta({"to_hit_die": '1d4'})
