from enum import Enum, auto
from abc import ABC, abstractmethod

from simulator.actions.actoid import FactoryFlags
from simulator.misc import roll_dice


class Factory:
    def __init__(self):
        self.flags = FactoryFlags.DEFAULT


class Threat(ABC):

    @abstractmethod
    def calculate_threat(self, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return 0

    def calculate_threat_for_attack(self, combatant, attack, *args, **kwargs):
        """
        This is here so that we don't have to sort out AttackThreatModifier from other threats with if statements
        """
        return 0

    def clear_cache(self):
        """
        As this is the most frequently called method, it makes sense to cache it.
        """
        pass
        # self.calculate_threat.cache_clear()

class DirectThreat(Threat):
    """
    Direct dmg causing ability, directly healing ability or an ability that directly prevents dmg
    """


    @abstractmethod
    def calculate_threat_delta(self, modifiers, *args, **kwargs):
        """
        The delta in threat when modifiers are applied on this ability.
        """
        return 0




class AttackThreatModifier(Threat):
    """
    Ability that directly modifies threat of another attack ability. This is a more specialized variant of the ThreatModifier.
    They may be combined.
    """

    @abstractmethod
    def calculate_threat_for_attack(self, combatant, attack, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return 0


class AoEThreat(ABC):
    """
    AoE ability causing threat
    """

    @abstractmethod
    def threat_on_enter(self, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability upon entering the AoE
        """
        return 0

    @abstractmethod
    def threat_on_move_within(self, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability when moving within the AoE
        """
        return 0

    @abstractmethod
    def threat_on_start_of_turn(self, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability upon starting combatant's turn in the AoE
        """
        return 0

    @abstractmethod
    def threat_on_end_of_turn(self, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability upon end combatant's turn in the AoE
        """
        return 0


class ThreatModifierFactory(ABC, Factory):
    """
    Threat calculation for factories that modify threat of other abilities (buffs and debuffs). This kind of factory doesn't support
    the calculation of modification by other ThreatModifierFactory to avoid endless loops.
    """

    @abstractmethod
    def calculate_threat_to_target(self, target, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target by modifying other factories.
        This is useful for calculating threat_in from the abilities of enemies
        """
        return 0

class DirectThreatFactory(ABC, Factory):

    def __init__(self):
        Factory.__init__(self)
        self.flags |= FactoryFlags.IS_DIRECT_THREAT

    """
    Threat calculation for factories. They compute an estimation of the threat potential based on its stats.
    It also mandates that a factory be able to compute a threat increment based on a dictionary of modified stats
    """
    @abstractmethod
    def calculate_threat_to_target(self, target, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        return 0

    @abstractmethod
    def calculate_threat_to_target_delta(self, target, modifiers, *args, **kwargs):
        """
        Calculates the threat delta of the factory to a specific target given stat modifications.
        This is useful calculating the potential reduction of threat_in caused by abilities of enemies, e.g. advantage on saving throw
        against fireball or bane on attack rolls etc.
        """
        return 0

class RechargeFactory(ABC, Factory):

    def __init__(self, recharge_value):
        Factory.__init__(self)
        self.recharge_value = recharge_value
        self.flags |= FactoryFlags.IS_RECHARGE

    def roll_for_recharge(self):
        roll = roll_dice([1, 6])
        if roll >= self.recharge_value:
            self.combatant.ammo[self.name] = 1

class TransformerFactory(Threat, Factory):

    """
    A factory that modifies the user and the factories they have at their disposal
    """
    pass
