from enum import Enum, auto
from abc import ABC, abstractmethod

from simulator.action_types import BonusActionOrdering
from simulator.actions.actoid import FactoryFlags


class Factory:
    def __init__(self):
        self.flags = FactoryFlags.DEFAULT
        self.bonus_action_ordering = BonusActionOrdering.INDEPENDENT


    @abstractmethod
    def create_mock(self):
        """
        Every factory needs to have this in order to build the action FSM for each combatant.
        """
        pass

class DirectThreat(ABC):
    """
    Direct dmg causing ability, directly healing ability or an ability that directly prevents dmg
    """

    @abstractmethod
    def calculate_threat(self, combatant, battle_map, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return 0


class ThreatModifier(ABC):
    """
    Ability that modifies threat of other abilities
    """
    # @abstractmethod
    # @staticmethod
    # def calculate_threat_mod_approx(combatant, battle_map, actions, *args, **kwargs):
    #     return 0

    @abstractmethod
    def calculate_threat(self, combatant, battle_map, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return 0

class ReactionToThreat(ABC):
    """
    An ability that has the potential to mitigate an incoming threat
    """
    # TODO Do I really need this?

    @abstractmethod
    def calculate_threat_mod(self, combatant, battle_map, incoming_action, actor, *args, **kwargs):
        return 0


class ThreatModifierFactory(ABC, Factory):
    """
    Threat calculation for factories that modify threat of other abilities (buffs and debuffs). This kind of factory doesn't support
    the calculation of modification by other ThreatModifierFactory to avoid endless loops.
    """

    @abstractmethod
    def calculate_threat_to_target(self, battle_map, target, *args, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target by modifying other factories.
        This is useful for calculating threat_in from the abilities of enemies
        """
        return 0

    @abstractmethod
    def calculate_threat_to_target_using_attack(self, battle_map, target, attack_factory, *args, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target by modifying a specific given factory.
        This is used to construct the threat adjacency matrix.
        """
        return 0

class DirectThreatFactory(ABC, Factory):

    def __init__(self):
        Factory.__init__(self)
        self.flags |= FactoryFlags.IS_DIRECT_THREAT

    """
    Threat calculation for factories. They compute an estimation of the threat potential based on its stats.
    It also mandates that a factory be able to compute a threat increment based on a dictionary of modified stats
    """
    @abstractmethod
    def calculate_threat_approx_mod(self, battle_map, modified_stats, *args, **kwargs):
        """
        Calculates the threat delta of the factory given stat modifications. This is a general estimation with no specific target.
        This is useful for evaluation the threat_out of (de)buff abilities. It's meant to be called from the threat calculation methods
        of (de)buff abilities.
        """
        return 0

    @abstractmethod
    def calculate_threat_to_target(self, battle_map, target, *args, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        return 0

    @abstractmethod
    def calculate_threat_to_target_mod(self, battle_map, target, modified_stats, *args, **kwargs):
        """
        Calculates the threat delta of the factory to a specific target given stat modifications.
        This is useful calculating the potential reduction of threat_in caused by abilities of enemies, e.g. advantage on saving throw
        against fireball or bane on attack rolls etc.
        """
        return 0

class AoEThreatFactory(ABC):
    """
    AoE ability causing threat
    """

    @abstractmethod
    def threat_on_enter(self, battle_map, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability upon entering the AoE
        """
        return 0

    @abstractmethod
    def threat_on_start_of_turn(self, battle_map, target,  *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability upon starting combatant's turn in the AoE
        """
        return 0

    @abstractmethod
    def threat_on_end_of_turn(self, battle_map, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability upon end combatant's turn in the AoE
        """
        return 0
