from abc import ABC, abstractmethod

from .actions.actoid import Actoid, ActoidFlags

class Threat(ABC):

    @abstractmethod
    def calculate_threat(self, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return 0

    def calculate_threat_for_attack(self, combatant, attack, *args, **kwargs):
        """
        This is here so that we don't have to sort out AttackThreatModifier from other threats with if statements
        """
        return 0

    def clear_cache(self):
        """
        As this is the most frequently called method, it makes sense to cache it.
        """
        pass
        # self.calculate_threat.cache_clear()


class DirectThreat(Threat):
    """
    Direct dmg causing ability, directly healing ability or an ability that directly prevents dmg
    """

    @abstractmethod
    def calculate_threat_delta(self, modifiers, *args, **kwargs):
        """
        The delta in threat when modifiers are applied on this ability.
        """
        return 0


class AttackThreatModifier(Actoid, Threat):
    """
    Ability that directly modifies threat of another attack ability. This is a more specialized variant of the ThreatModifier.
    They may be combined.
    """

    def __init__(self, actoid_flags=ActoidFlags.DEFAULT):
        Actoid.__init__(self, actoid_flags)
        self.actoid_flags |= ActoidFlags.IS_ATTACK_MODIFIER

    @abstractmethod
    def calculate_threat_for_attack(self, combatant, attack, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return 0


class AoEThreat(ABC):
    """
    AoE ability causing threat
    """

    @abstractmethod
    def threat_on_enter(self, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability upon entering the AoE
        """
        return 0

    @abstractmethod
    def threat_on_move_within(self, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability when moving within the AoE
        """
        return 0

    @abstractmethod
    def threat_on_start_of_turn(self, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability upon starting combatant's turn in the AoE
        """
        return 0

    @abstractmethod
    def threat_on_end_of_turn(self, target, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability upon end combatant's turn in the AoE
        """
        return 0
