from enum import Enum, auto


class Action(Enum):
    NOP = auto()
    MELEE_ATTACK = auto()
    RANGED_ATTACK = auto()
    RECKLESS_ATTACK = auto()
    PRE_SWALLOW_BITE = auto()
    BITE_AND_SWALLOW = auto()
    DODGE = auto()
    DASH = auto()
    DISENGAGE = auto()
    FIREBALL = auto()
    FIREBOLT = auto()
    CHAOSBOLT = auto()
    HASTE = auto()
    HUNGER_OF_HADAR = auto()
    SPIKE_GROWTH = auto()
    CLOUD_OF_DAGGERS = auto()
    HIDE = auto()
    TWINNED_FIREBOLT = auto()
    TWINNED_HASTE = auto()
    SCORCHING_RAY = auto()
    FAERIE_FIRE = auto()
    WILDSHAPE = auto()
    POUNCE = auto()
    CONSTRICT = auto()
    BREAK_GRAPPLE = auto()
    FLAMING_SPHERE = auto()
    WEB = auto()
    HOLD_PERSON = auto()
    TWINNED_HOLD_PERSON = auto()
    SHOCKING_GRASP = auto()
    TWINNED_SHOCKING_GRASP = auto()
    MAGIC_MISSILE = auto()
    GRAPPLE = auto()
    GRAPPLE_ATTACK = auto()
    VAMPIRIC_BITE = auto()
    BLESS = auto()
    RAY_OF_ENFEEBLEMENT = auto()
    TWINNED_RAY_OF_ENFEEBLEMENT = auto()
    SLEEP = auto()
    SHAKE_ALLY_AWAKE = auto()
    THUNDERWAVE = auto()
    MENACING_MELEE_ATTACK = auto()
    PARALYZING_MELEE_ATTACK = auto()
    # PRECISION_MELEE_ATTACK = auto()
    MENACING_RANGED_ATTACK = auto()
    # PRECISION_RANGED_ATTACK = auto()
    PRECISION_ATTACK = auto()
    LAY_ON_HANDS = auto()
    CURE_WOUNDS = auto()
    ABJURE_ENEMY = auto()
    CONIC_BREATH_WEAPON = auto()
    CONIC_BREATH_WEAPON_ATTACK = auto()
    LINE_BREATH_WEAPON = auto()
    RAY_OF_FROST = auto()


class BonusAction(Enum):
    NOP = auto()
    BONUS_MELEE_ATTACK = auto()
    BONUS_RANGED_ATTACK = auto()
    PAM_BONUS_ATTACK = auto()
    RAGE = auto()
    TOTEM_RAGE = auto()
    MISTY_STEP = auto()
    CUNNING_DISENGAGE = auto()
    CUNNING_DASH = auto()
    CUNNING_HIDE = auto()
    QUICKENED_FIREBALL = auto()
    QUICKENED_FIREBOLT = auto()
    QUICKENED_CHAOSBOLT = auto()
    QUICKENED_HASTE = auto()
    QUICKENED_HUNGER_OF_HADAR = auto()
    QUICKENED_SPIKE_GROWTH = auto()
    QUICKENED_CLOUD_OF_DAGGERS = auto()
    QUICKENED_SCORCHING_RAY = auto()
    QUICKENED_FAERIE_FIRE = auto()
    QUICKENED_BLESS = auto()
    QUICKENED_FLAMING_SPHERE = auto()
    QUICKENED_HOLD_PERSON = auto()
    QUICKENED_RAY_OF_FROST = auto()
    FLAMING_SPHERE_RAM = auto()
    MOON_WILDSHAPE = auto()
    QUICKENED_SHOCKING_GRASP = auto()
    QUICKENED_MAGIC_MISSILE = auto()
    QUICKENED_RAY_OF_ENFEEBLEMENT = auto()
    QUICKENED_SLEEP = auto()
    SECOND_WIND = auto()
    HEALING_WORD = auto()
    TWINNED_HEALING_WORD = auto()
    SHILLELAGH = auto()
    QUICKENED_THUNDERWAVE = auto()
    BONUS_MENACING_MELEE_ATTACK = auto()
    # BONUS_PRECISION_MELEE_ATTACK = auto()
    BONUS_MENACING_RANGED_ATTACK = auto()
    # BONUS_PRECISION_RANGED_ATTACK = auto()
    SHIELD_OF_FAITH = auto()
    QUICKENED_CURE_WOUNDS = auto()
    VOW_OF_ENMITY = auto()
    AGGRESSIVE = auto()


class Reaction(Enum):
    REACTION_ATTACK = auto()
    SHIELD = auto()
    PRE_SWALLOW_BITE_REACTION = auto()
    UNCANNY_DODGE = auto()
    PARRY = auto()
    RIPOSTE = auto()
    REACTION_PARALYZING_MELEE_ATTACK = auto()


class Movement(Enum):
    STANDARD = auto()
    DISENGAGED = auto()
    FORCED = auto()
    GET_UP_FROM_PRONE = auto()
    DASH = auto()


class MovementThreatType(Enum):
    STANDARD = auto()
    DISENGAGED = auto()
    DODGED = auto()
    MISTY_STEPPED = auto()


class HasteAction(Enum):
    HASTE_MELEE_ATTACK = auto()
    HASTE_RANGED_ATTACK = auto()
    HASTE_DASH = auto()
    HASTE_DISENGAGE = auto()
    HASTE_HIDE = auto()
    HASTE_PRE_SWALLOW_BITE = auto()
    HASTE_BITE_AND_SWALLOW = auto()
    HASTE_GRAPPLE_ATTACK = auto()
    HASTE_GRAPPLE = auto()
    HASTE_VAMPIRIC_BITE = auto()
    HASTE_PARALYZING_MELEE_ATTACK = auto()


class Passive(Enum):
    SPELLCASTING = auto()
    SENTINEL = auto()
    POLEARM_MASTER = auto()
    DANGER_SENSE = auto()
    METAMAGIC = auto()
    PACK_TACTICS = auto()
    FANATIC_ADVANTAGE = auto()
    WAR_CASTER = auto()
    ELDRITCH_MIND = auto()
    SNEAK_ATTACK = auto()
    CUNNING_ACTION = auto()
    ASSASSINATE = auto()
    REGENERATION = auto()
    EVASION = auto()
    HEART_OF_HRUGGEK = auto()
    DARK_DEVOTION = auto()
    BLINDSIGHT = auto()
    MAGIC_RESISTANCE = auto()
    CHARM_IMMUNITY = auto()
    GREAT_WEAPON_FIGHTING = auto()
    DUELING = auto()
    BATTLE_MASTER_MANEUVERS = auto()
    DRACONIC_RESILIENCE = auto()
    UNARMORED_DEFENSE = auto()
    DIVINE_SMITE = auto()
    CHANNEL_DIVINITY = auto()
    UNDEAD_FORTITUDE = auto()
    MARTIAL_ADVANTAGE = auto()


class MetaAction(Enum):
    QUICKENED_SPELL = auto()
    TWINNED_SPELL = auto()
    EMPOWERED_SPELL = auto()


# TODO
class FreeAction(Enum):
    ACTION_SURGE = auto()
