from functools import cache
from simulator.abilities.on_hit_sneak_attack import OnHitSneakAttack
from simulator.actions.action_types import HasteAction, BonusAction
from simulator.actions.actoid import Actoid, ActoidFlags, FactoryFlags
from simulator.battle_map import Map
from simulator.effects.combatant_effect import CombatantEffect
from simulator.effects.effect import EffectType
from simulator.misc import Visibility, roll_ability_check, Conditions
from simulator.threat_interfaces import ThreatModifierFactory, AttackThreatModifier
import logging

from simulator.threat_utils import calc_p_hit
from simulator.utils.roll_types import RollType, ThreatModifierType, ROLL_TYPE_DELTA

logger = logging.getLogger("Encounterra")

class HideFactory(ThreatModifierFactory):

    def __init__(self, action_type, combatant):
        super().__init__()
        self.combatant = combatant
        self.action_type = action_type  # DISENGAGE, CUNNING_DISENGAGE

    def __str__(self):
        """
        Important for FSM building
        """
        return "HideFactory"

    def get_kwargs(self):
        return {'combatant': self.combatant, 'action_type': self.action_type}

    def create_all(self):
        if self.combatant.get_swallower():
            return None
        battle_map = Map.get()
        return [Hide(e, self) for e in Map.get().get_enemies(self.combatant) if not battle_map.effect_tracker.is_combatant_hidden_from(self.combatant, e)]


    def create(self, target):
        return Hide(target, self)

    def calculate_threat_to_target(self, target, **kwargs):
        """
        Calculates the direct AoO threat the disengage would avoid
        """
        return 0  # Keep at 0 since we only want to hide in order to attack, the threat will be added as an attack modifier


class Hide(Actoid, CombatantEffect, AttackThreatModifier):

    def __init__(self, target, factory):
        Actoid.__init__(self, actoid_flags=ActoidFlags.IS_HIDE)
        CombatantEffect.__init__(self, combatants=[factory.combatant])
        self.target = target
        self.factory = factory

    def get_effect_type(self):
        return EffectType.HIDE

    def __str__(self):
        prefix = ""
        if self.factory.action_type is BonusAction.CUNNING_HIDE:
            prefix = "Cunning "
        elif self.factory.action_type is HasteAction.HASTE_HIDE:
            prefix = "Hasted "
        return prefix + f"Hide of {self.factory.combatant} from {self.target}"

    def shorthand_str(self):
        prefix = ""
        if self.factory.action_type is BonusAction.CUNNING_HIDE:
            prefix = "Cunning "
        elif self.factory.action_type is HasteAction.HASTE_HIDE:
            prefix = "Hasted "
        return prefix + f"Hide"

    def activate(self):
        if roll_ability_check(self.factory.combatant.stealth, self.target.passive_perception + 1, RollType.STRAIGHT):
            logger.info(f"{self.factory.combatant} is hidden from {self.target}")
            Map.get().effect_tracker.add(self)
        else:
            logger.info(f"{self.factory.combatant} fails to hide from {self.target}")

    def deactivate(self):
        logger.info(f"{self.factory.combatant} is no longer hidden {self.target}")

    def calculate_threat(self, **kwargs):
        return 0

    def calculate_threat_for_attack(self, combatant, attack, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        if getattr(attack, "target", None) is self.target and (FactoryFlags.IS_ATTACK_LIKE in attack.factory.flags or
                                                             (FactoryFlags.IS_FINESSE in attack.factory.flags or
                                                              FactoryFlags.IS_RANGED in attack.factory.flags))\
                and self.factory.combatant.movement > 0:  # Have to be able to pop out of cover
            battle_map = Map.get()
            threat_acc = attack.calculate_threat_delta({ThreatModifierType.ROLL_TYPE: RollType.ADVANTAGE})
            assert threat_acc > 0
            if battle_map.is_ally_adjacent_to_target(combatant, attack.target):
                return threat_acc  # Sneak Attack condition already met, no extra benefit
            if isinstance(attack.factory.on_hit, OnHitSneakAttack):
                to_hit_total = attack.factory.to_hit + ROLL_TYPE_DELTA[RollType.ADVANTAGE][max(0, min(attack.target.ac - attack.factory.to_hit, 20))]
                threat_acc += calc_p_hit(to_hit_total, attack.target.ac) * attack.factory.on_hit.calculate_threat(combatant, attack.target, roll_type=RollType.ADVANTAGE)
            return threat_acc
        else:
            return 0

    def get_eligible_coords(self, distances, shortest_paths):
        if self.factory.combatant.get_swallower():
            return set()
        battle_map = Map.get()
        if self.factory.combatant.movement > 0 and not self.factory.combatant.is_affected_by_any(Conditions.GRAPPLED, Conditions.GRAPPLING, Conditions.RESTRAINED):
            return {coord for coord, vis_dict in battle_map.visibility_dict_for_all_coords.items() if vis_dict[self.target] is Visibility.NONE}
        elif battle_map.visibility_dict_for_all_coords[tuple(battle_map.get_combatant_position(self.factory.combatant).get()[0])][self.target] is Visibility.NONE:
            return set(tuple(battle_map.get_combatant_position(self.factory.combatant).get()[0]))
        return set()
