from simulator.actions.action_types import HasteAction, BonusAction
from simulator.actions.actoid import Actoid, ActoidFlags
from simulator.battle_map import Map
from simulator.effects.combatant_effect import CombatantEffect
from simulator.effects.effect import EffectType, Effect
from simulator.misc import Visibility, roll_ability_check
from simulator.threat_interfaces import ThreatModifier, ThreatModifierFactory, AttackThreatModifier
import logging

from simulator.utils.roll_types import RollType

logger = logging.getLogger("EncounTroll")

class HideFactory(ThreatModifierFactory):

    def __init__(self, action_type, combatant):
        super().__init__()
        self.combatant = combatant
        self.action_type = action_type  # DISENGAGE, CUNNING_DISENGAGE

    def __str__(self):
        """
        Important for FSM building
        """
        return "HideFactory"

    def get_kwargs(self):
        return {'combatant': self.combatant, 'action_type': self.action_type}

    def create_all(self):
        if self.combatant.get_swallower():
            return None
        return [Hide(t, self) for t in Map.get().get_enemies(self.combatant)]


    def create(self, target):
        return Hide(target, self)

    def calculate_threat_to_target(self, target, **kwargs):
        """
        Calculates the direct AoO threat the disengage would avoid
        """
        return 0  # Keep at 0 since we only want to hide in order to attack, the threat will be added as an attack modifier


class Hide(Actoid, CombatantEffect, AttackThreatModifier):

    def __init__(self, target, factory):
        Actoid.__init__(self, actoid_flags=ActoidFlags.IS_HIDE)
        CombatantEffect.__init__(self, combatants=[factory.combatant])
        self.target = target
        self.factory = factory

    def get_effect_type(self):
        return EffectType.HIDE

    def __str__(self):
        prefix = ""
        if self.factory.action_type is BonusAction.CUNNING_HIDE:
            prefix = "Cunning "
        elif self.factory.action_type is HasteAction.HASTE_HIDE:
            prefix = "Hasted "
        return prefix + f"Hide of {self.factory.combatant}"

    def shorthand_str(self):
        prefix = ""
        if self.factory.action_type is BonusAction.CUNNING_HIDE:
            prefix = "Cunning "
        elif self.factory.action_type is HasteAction.HASTE_HIDE:
            prefix = "Hasted "
        return prefix + f"Hide"

    def activate(self):
        logger.info(f"{self.factory.combatant} attempts to hide from {self.target}")
        battle_map = Map.get()
        curr_visibility = battle_map.visibility_dict_for_all_coords[tuple(battle_map.get_combatant_position(self.factory.combatant))]
        for enemy in curr_visibility.keys():
            if roll_ability_check(self.factory.combatant.stealth, enemy.passive_perception + 1, RollType.STRAIGHT):
                logger.info(f"{self.factory.combatant} is hidden from {self.target}")
                Map.get().effect_tracker.add(self)
            else:
                logger.info(f"{self.factory.combatant} fails to hide from {self.target}")

    def deactivate(self):
        logger.info(f"{self.factory.combatant} is no longer hidden {self.target}")


    # def calculate_threat(self, **kwargs):
    #     """
    #     Calculate how much dmg would the Disengage potentially mitigate. This will be the same as the one for the factory.
    #     """
    #     return 0  # Keep at 0 since we only want to hide in order to attack, the threat will be added as an attack modifier

    def calculate_threat_for_attack(self, combatant, attack, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        # rage_bonus = RageFactory.get_rage_bonus(combatant.level)
        # if FactoryFlags.IS_MELEE in attack.factory.flags:
        #     return attack.calculate_threat_delta({ThreatModifierType.DMG_BONUS_FLAT: rage_bonus})
        return 0  # TODO

    def get_eligible_coords(self, distances, shortest_paths):
        return [coord for coord, vis_dict in Map.get().visibility_dict_for_all_coords.items() if vis_dict[self.target] is Visibility.NONE]

    def is_current_coord_eligible(self):
        if self.factory.combatant.get_swallower():
            return False
        battle_map = Map.get()
        return battle_map.visibility_dict_for_all_coords[tuple(battle_map.get_combatant_position(self.factory.combatant))][self.target] is Visibility.NONE
