FROM --platform=linux/arm64 python:3.11
WORKDIR /app
COPY . .
RUN rm core_entrypoint.py

# Upgraded from 1.5.1 due to https://github.com/python-poetry/poetry/issues/7611
ARG POETRY_VERSION=1.6.1
RUN pip install --upgrade pip \
 && pip install poetry==${POETRY_VERSION} \
 && poetry config virtualenvs.create false \
 && poetry install --no-interaction --without dev

ENTRYPOINT ["python", "ecs_core_entrypoint.py"]