from simulator.combatant import Combatant
from simulator.spellslots import Spellslots
from simulator.action_factory import *
import logging

logger = logging.getLogger(__name__)


class TraineeFaurung(Combatant):

    def __init__(self):
        super().__init__("Faurung", level=5, hp=43, ac=16, init_bonus=2, speed=30, spell_to_hit=7, resistances=set(), dc=15)
        self.add_ability(Action.FIREBALL)
        self.add_ability(Action.FIREBOLT)
        self.add_ability(Action.HASTE)
        self.add_ability(BonusAction.MISTY_STEP)
        self.add_ability(Reaction.SHIELD)
        self.add_ability(Passive.METAMAGIC, sorcery_points=5)
        self.add_ability(MetaAction.QUICKENED_SPELL)
        self.add_ability(MetaAction.TWINNED_SPELL)
        self.spellslots = Spellslots(Spellslots.Class.SORCERER, 5)
        self.movement_generator_cache = None
        self.nowhere_to_go = False

    def get_action(self, battle_map):
        # Not used. Action is generated by the RL model instead
        return (None,)

    def new_turn(self):
        super().new_turn()


    def prompt_aoo(self, moving_combatant):
        return (None,)

    def prompt_after_hit_reaction(self, attacking_combatant):
        if self.spellslots.get_spellslots(1) and self.has_reaction:
            logger.debug(f"{self.name} casts Shield", extra={"team": self.team_color})
            return (Reaction.SHIELD,)
        elif self.has_reaction:
            logger.debug(f"{self.name} cannot cast Shield. Out of spellslots.", extra={"team": self.team_color})
        return (None,)
