from simulator.actions.action_types import Action
from simulator.actions.actoid import FactoryFlags, Actoid, ActoidFlags
from simulator.threat_interfaces import DirectThreatFactory, DirectThreat
import logging


logger = logging.getLogger("EncounTroll")

class ConstrictFactory(DirectThreatFactory):
    """
    The is_constricting variable is the reason why this is modeled as a separate ability rather than an attack with an on_hit effect
    """

    def __init__(self, combatant, attack):
        DirectThreatFactory.__init__(self)
        self.combatant = combatant
        self.attack = attack
        self.action_type = Action.CONSTRICT
        self.flags |= FactoryFlags.IS_MELEE


    def __str__(self):
        return "ConstrictFactory"

    def get_eligible_targets(self, battle_map):
        return battle_map.get_enemies(self.combatant)

    def create(self, target_combatant):
        if self.combatant.is_constricting:
            return None
        return Constrict(target_combatant, self)

    def create_all(self, battle_map):
        if self.combatant.is_constricting:
            return None
        targets = self.get_eligible_targets(battle_map)
        return [Constrict(t, self) for t in targets]

    def calculate_threat_to_target(self, battle_map, target, *args, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        # TODO include the threat of the RESTRAINED and GRAPPLED in the calculation
        return self.attack.calculate_threat_to_target(battle_map, target)

    def calculate_threat_to_target_delta(self, battle_map, target, modified_stats, *args, **kwargs):
        """
        Calculates the threat delta of the factory to a specific target given stat modifications.
        This is useful calculating the potential reduction of threat_in caused by abilities of enemies, e.g. advantage on saving throw
        against fireball or bane on attack rolls etc.
        """
        return self.attack.calculate_threat_to_target_delta(battle_map, target, modified_stats)



class Constrict(Actoid, DirectThreat):

    def __init__(self, target_combatant, factory):
        Actoid.__init__(self, actoid_flags=ActoidFlags.IS_ATTACK_LIKE | ActoidFlags.IS_DIRECT_THREAT)
        self.target_combatant = target_combatant
        self.factory = factory

    def __str__(self):
        return f"Constrict on {self.target_combatant}"

    def shorthand_str(self):
        return "Constrict"

    def get_eligible_coords(self, battle_map, distances, shortest_paths):
        return battle_map.get_free_coords_in_hop_range(battle_map.get_combatant_position(self.target_combatant),
                                                       distances,
                                                       inflate_to_size=self.factory.combatant.size,
                                                       rng=1,
                                                       combatant=self.factory.combatant)

    def is_current_coord_eligible(self, battle_map):
        return battle_map.are_in_hop_range(self.factory.combatant, self.target_combatant, self.factory.attack.range)

    def calculate_threat(self, combatant, battle_map, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return self.factory.calculate_threat_to_target(battle_map, self.target_combatant)

    def calculate_threat_delta(self, battle_map, modified_stats, *args, **kwargs):
        """
        The delta in threat when modified_stats are applied on this ability.
        """
        return self.factory.calculate_threat_to_target_delta(battle_map, self.target_combatant, modified_stats)