from simulator.actions.action_types import Action
from simulator.actions.actoid import FactoryFlags, Actoid, ActoidFlags
from simulator.battle_map import Map
from simulator.misc import Conditions
from simulator.threat_interfaces import DirectThreatFactory, DirectThreat
import logging


logger = logging.getLogger("EncounTroll")

class ConstrictFactory(DirectThreatFactory):
    """
    The constricted_target variable is the reason why this is modeled as a separate ability rather than an attack with an on_hit effect
    """

    def __init__(self, combatant, attack):
        DirectThreatFactory.__init__(self)
        self.combatant = combatant
        self.attack = attack
        self.action_type = Action.CONSTRICT
        self.flags |= FactoryFlags.IS_MELEE


    def __str__(self):
        return "ConstrictFactory"

    def get_eligible_targets(self):
        swallower = self.combatant.get_swallower()
        if swallower:
            return []  # Doesn't make sense to constrict anyone from the inside
        battle_map = Map.get()
        return [e for e in battle_map.get_enemies(self.combatant) if not e.is_affected_by(Conditions.SWALLOWED)]

    def create(self, target_combatant):
        if self.combatant.constricted_target is None or self.combatant.constricted_target is target_combatant:
            return Constrict(target_combatant, self)
        return None


    def create_all(self):
        if self.combatant.constricted_target is not None:
            return [Constrict(self.combatant.constricted_target)]
        targets = self.get_eligible_targets()
        return [Constrict(t, self) for t in targets]

    def calculate_threat_to_target(self, target, *args, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        # TODO include the threat of the RESTRAINED and GRAPPLED in the calculation
        return self.attack.calculate_threat_to_target(target)

    def calculate_threat_to_target_delta(self, target, modifiers, *args, **kwargs):
        """
        Calculates the threat delta of the factory to a specific target given stat modifications.
        This is useful calculating the potential reduction of threat_in caused by abilities of enemies, e.g. advantage on saving throw
        against fireball or bane on attack rolls etc.
        """
        return self.attack.calculate_threat_to_target_delta(target, modifiers)

    def calculate_max_threat(self):
        targets = self.get_eligible_targets()
        return max([self.calculate_threat_to_target(t) for t in targets])



class Constrict(Actoid, DirectThreat):

    def __init__(self, target_combatant, factory):
        Actoid.__init__(self, actoid_flags=ActoidFlags.IS_ATTACK_LIKE | ActoidFlags.IS_DIRECT_THREAT)
        self.target_combatant = target_combatant
        self.factory = factory

    def __str__(self):
        return f"Constrict on {self.target_combatant}"

    def shorthand_str(self):
        return "Constrict"

    def get_eligible_coords(self, distances, shortest_paths):
        battle_map = Map.get()
        return battle_map.get_free_coords_in_hop_range(battle_map.get_combatant_position(self.target_combatant),
                                                       distances,
                                                       inflate_to_size=self.factory.combatant.size,
                                                       rng=1,
                                                       combatant=self.factory.combatant)

    def is_current_coord_eligible(self):
        battle_map = Map.get()
        return battle_map.are_in_hop_range(self.factory.combatant, self.target_combatant, self.factory.attack.range)

    def calculate_threat(self, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return self.factory.calculate_threat_to_target(self.target_combatant)

    def calculate_threat_delta(self, modifiers, *args, **kwargs):
        """
        The delta in threat when modifiers are applied on this ability.
        """
        return self.factory.calculate_threat_to_target_delta(self.target_combatant, modifiers)