from cachetools.keys import hashkey

from ..actions.action_types import Action
from ..actions.actoid import FactoryFlags, Actoid, ActoidFlags
from ..battle_map import Map, map_position_toggled_cache, map_toggled_cache_with_key
from ..misc import Conditions
from ..threat_interfaces import DirectThreatFactory, DirectThreat
from ..threat_utils import get_saving_throw_success_prob
import logging

logger = logging.getLogger("Encounterra")

class PounceFactory(DirectThreatFactory):

    def __init__(self, combatant, primary_attack, secondary_attack, distance):
        DirectThreatFactory.__init__(self)
        self.combatant = combatant
        self.primary_attack = primary_attack
        self.secondary_attack = secondary_attack
        self.distance = distance
        self.action_type = Action.POUNCE
        self.flags |= FactoryFlags.IS_MELEE


    def __str__(self):
        return "PounceFactory"

    def get_ability_name(self):
        return "Pounce"

    def get_eligible_targets(self):
        swallower = self.combatant.get_swallower()
        if swallower:
            return []
        battle_map = Map.get()
        return [e for e in battle_map.get_enemies_without_hop_distance(self.combatant, self.distance - 1) if not e.is_affected_by(Conditions.SWALLOWED)]

    def create(self, target):
        return Pounce(target, self)

    def create_all(self):
        targets = self.get_eligible_targets()
        return [Pounce(t, self) for t in targets]

    def calculate_threat_to_target(self, target, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        # TODO include the threat of the PRONE in the calculation
        p_fail = 1 - get_saving_throw_success_prob(self.primary_attack.on_hit.dc, target.saving_throws[self.primary_attack.on_hit.st])
        return self.primary_attack.calculate_threat_to_target(target) + p_fail * self.secondary_attack.calculate_threat_to_target(target)

    def calculate_threat_to_target_delta(self, target, modifiers, *args, **kwargs):
        """
        Calculates the threat delta of the factory to a specific target given stat modifications.
        This is useful calculating the potential reduction of threat_in caused by abilities of enemies, e.g. advantage on saving throw
        against fireball or bane on attack rolls etc.
        """
        p_fail = 1 - get_saving_throw_success_prob(self.primary_attack.on_hit.dc, target.saving_throws[self.primary_attack.on_hit.st])
        return self.primary_attack.calculate_threat_to_target_delta(target, modifiers) + p_fail * self.secondary_attack.calculate_threat_to_target_delta(target, modifiers)

    def calculate_max_threat(self):
        targets = self.get_eligible_targets()
        return max([self.calculate_threat_to_target(t) for t in targets])


class Pounce(Actoid, DirectThreat):

    def __init__(self, target, factory):
        Actoid.__init__(self, actoid_flags=ActoidFlags.IS_ATTACK_LIKE)
        self.target = target
        self.factory = factory

    def __str__(self):
        return f"Pounce on {self.target}"

    def shorthand_str(self):
        return "Pounce"

    #@map_toggled_cache_with_key(key=lambda self, distances, shortest_paths: hashkey(self.factory.name, tuple(Map.get().get_combatant_position(self.factory.combatant).get()[0])))
    def get_eligible_coords(self, distances, shortest_paths):
        battle_map = Map.get()
        if not self.factory.combatant.is_affected_by_any(Conditions.GRAPPLED, Conditions.GRAPPLING, Conditions.RESTRAINED):
            return battle_map.get_free_coords_in_hop_range(battle_map.get_combatant_position(self.target),
                                                           distances,
                                                           inflate_to_size=self.factory.combatant.size + self.factory.distance,
                                                           rng=battle_map.size,  # approximation, could theoretically be longer
                                                           combatant=self.factory.combatant)
        elif battle_map.get_hop_distance_combatants(self.factory.combatant, self.target) >= self.factory.distance:
            return [tuple(battle_map.get_combatant_position(self.factory.combatant).get()[0])]
        return None

    @map_position_toggled_cache
    def calculate_threat(self, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return self.factory.calculate_threat_to_target(self.target)

    def clear_cache(self):
        self.calculate_threat.cache_clear()
        self.calculate_threat_delta.cache_clear()
        #self.get_eligible_coords.cache_clear()

    @map_toggled_cache_with_key(key=lambda self, modifiers, *args, **kwargs: hashkey(self.factory.name, tuple(modifiers.items()), tuple(Map.get().get_combatant_position(self.factory.combatant).get()[0])))
    def calculate_threat_delta(self, modifiers, *args, **kwargs):
        """
        The delta in threat when modifiers are applied on this ability.
        """
        return self.factory.calculate_threat_to_target_delta(self.target, modifiers)
