from ..battle_map import Map, PLACEHOLDER_MAPPING
from ..effects.effect import EffectType
from ..misc import  Visibility
from ..conditions import Conditions, is_affected_by_any, get_swallower
from ..actions.actoid import Actoid, FactoryFlags
from ..effects.combatant_effect import CombatantEffect
from ..effects.limited_duration_effect import LimitedDurationEffect
from ..actions.action_types import BonusAction
from ..misc import ROUND_HORIZON
from ..threat_interfaces import AttackThreatModifier
from ..factory_interfaces import ThreatModifierFactory
import logging
import numba_functions as nf

from ..utils.roll_types import ThreatModifierType, RollType

logger = logging.getLogger("Encounterra")


class VowOfEnmityFactory(ThreatModifierFactory):

    def __init__(self, combatant):
        super().__init__()
        self.flags |= FactoryFlags.IS_ATTACK_MODIFIER
        self.combatant = combatant
        self.action_type = BonusAction.VOW_OF_ENMITY

    def __str__(self):
        """
        Important for FSM building
        """
        return "VowOfEnmity"

    def get_ability_name(self):
        return "Vow of Enmity"

    def get_eligible_targets(self):
        if get_swallower(self.combatant):
            return []
        battle_map = Map.get()
        return [e for e in battle_map.get_non_swallowed_enemies(self.combatant)]

    def create_all(self, previous_action_in_dag=None):
        targets = self.get_eligible_targets()
        return [VowOfEnmity(t, self) for t in targets]

    def create(self, target):
        # Doesn't make much sense here
        return VowOfEnmity(target, self)

    def calculate_threat_to_target(self, target, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        out_threat_max_delta_acc = 0
        max_threat = 0
        for f in self.combatant.action_factories:
            if FactoryFlags.IS_ATTACK_LIKE & f[1].flags and FactoryFlags.PREVENT_ENDLESS_RECURSION not in f[1].flags:  # Checks for any overlap in flags
                delta = f[1].calculate_threat_to_target_delta(target, {ThreatModifierType.ROLL_TYPE: RollType.ADVANTAGE})
                max_threat = max(delta, max_threat)
        out_threat_max_delta_acc += max_threat
        max_threat = 0
        for f in self.combatant.bonus_action_factories:
            if FactoryFlags.IS_ATTACK_LIKE & f[1].flags and FactoryFlags.PREVENT_ENDLESS_RECURSION not in f[1].flags:  # Checks for any overlap in flags
                delta = f[1].calculate_threat_to_target_delta(target, {ThreatModifierType.ROLL_TYPE: RollType.ADVANTAGE})
                max_threat = max(delta, max_threat)
        out_threat_max_delta_acc += max_threat
        max_threat = 0
        for f in self.combatant.haste_action_factories:
            if FactoryFlags.IS_ATTACK_LIKE & f[1].flags and FactoryFlags.PREVENT_ENDLESS_RECURSION not in f[1].flags:  # Checks for any overlap in flags
                delta = f[1].calculate_threat_to_target_delta(target, {ThreatModifierType.ROLL_TYPE: RollType.ADVANTAGE})
                max_threat = max(delta, max_threat)
        out_threat_max_delta_acc += max_threat
        return out_threat_max_delta_acc * ROUND_HORIZON


class VowOfEnmity(AttackThreatModifier, CombatantEffect, LimitedDurationEffect):

    def __init__(self, target, factory):
        AttackThreatModifier.__init__(self)
        CombatantEffect.__init__(self, factory.combatant, combatants=[target])
        LimitedDurationEffect.__init__(self, factory.combatant, turns=10)
        self.factory = factory

    def __str__(self):
        return f"Vow of Enmity on {self.combatants[0]}"

    def shorthand_str(self):
        return "Vow of Enmity"

    def get_effect_type(self):
        return EffectType.VOW_OF_ENMITY

    def activate(self, **kwargs):
        logger.info(f"{self.factory.combatant} uses {self}")
        Map.get().effect_tracker.add(self)

    def deactivate(self):
        logger.info(f"{self} fades")

    def deactivate_for_combatant(self, combatant):
        assert False

    def calculate_threat(self, **kwargs):
        """
        Finds the combatant's attack that benefits the most from the dmg increment. Then adds the estimated damage prevention equal to
        all remaining HP (better than regular rage)
        """
        return self.factory.calculate_threat_to_target(self.combatants[0])  # TODO: Maybe set this to 0?

    def calculate_threat_for_attack(self, combatant, attack, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        # TODO: I suspect the threat increase would be counter twice here which we don't want. First from calculate_threat then calculate_threat_for_attack
        try:
            return attack.calculate_threat_delta({ThreatModifierType.ROLL_TYPE: RollType.ADVANTAGE}) if attack.target is self.combatants[0] else 0
        except AttributeError:
            return 0

    #@map_toggled_cache_with_key(key=lambda self, distances, shortest_paths: hashkey(self.factory.name, tuple(Map.get().get_combatant_position(self.factory.combatant).get()[0])))
    def get_eligible_coords(self, distances, shortest_paths):
        if get_swallower(self.factory.combatant):
            return None, None
        battle_map = Map.get()
        curr_coord = tuple(battle_map.get_combatant_position(self.factory.combatant).get()[0])
        if not is_affected_by_any(self.factory.combatant, Conditions.GRAPPLED, Conditions.GRAPPLING, Conditions.RESTRAINED):
            free_coords_in_range = nf.get_free_coords_in_cartesian_range(
                battle_map.grid,
                battle_map.get_combatant_position(self.combatants[0]).get(),
                distances,
                self.factory.combatant.size.value,
                2, self.factory.combatant.id)
            return [coord for coord in free_coords_in_range if battle_map.visibility_dict_for_all_coords[coord][self.combatants[0]] is not Visibility.NONE], PLACEHOLDER_MAPPING
        elif battle_map.get_cartesian_distance_combatants(self.factory.combatant, self.combatants[0]) <= 2 and \
                battle_map.visibility_dict_for_all_coords[curr_coord][self.combatants[0]] is not Visibility.NONE:
            return [curr_coord], PLACEHOLDER_MAPPING
        return None, None
