from functools import cache

from cachetools.keys import hashkey

from simulator.actions.action_types import Action
from simulator.actions.actoid import FactoryFlags, Actoid, ActoidFlags
from simulator.battle_map import Map, map_position_toggled_cache, map_position_toggled_cache_with_key
from simulator.misc import Conditions
from simulator.threat_interfaces import DirectThreatFactory, DirectThreat, RechargeFactory
from simulator.threat_utils import get_saving_throw_success_prob
import logging

logger = logging.getLogger("EncounTroll")

class WebFactory(DirectThreatFactory, RechargeFactory):

    def __init__(self, combatant, attack, recharge):
        DirectThreatFactory.__init__(self)
        self.combatant = combatant
        self.attack = attack
        self.action_type = Action.WEB
        self.flags |= FactoryFlags.IS_RANGED


    def __str__(self):
        return "WebFactory"

    def get_eligible_targets(self):
        swallower = self.combatant.get_swallower()
        if swallower:
            return []  # Can hardly spin a web while being swallowed
        battle_map = Map.get()
        return [e for e in battle_map.get_enemies_without_hop_distance(self.combatant, self.distance - 1) if not e.is_affected_by(Conditions.SWALLOWED)]

    def create(self, target):
        return Web(target, self)

    def create_all(self):
        targets = self.get_eligible_targets()
        return [Web(t, self) for t in targets]

    def calculate_threat_to_target(self, target, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        # TODO include the threat of the PRONE in the calculation
        p_fail = 1 - get_saving_throw_success_prob(self.primary_attack.on_hit.dc, target.saving_throws[self.primary_attack.on_hit.st])
        return self.primary_attack.calculate_threat_to_target(target) + p_fail * self.secondary_attack.calculate_threat_to_target(target)

    def calculate_threat_to_target_delta(self, target, modifiers, *args, **kwargs):
        """
        Calculates the threat delta of the factory to a specific target given stat modifications.
        This is useful calculating the potential reduction of threat_in caused by abilities of enemies, e.g. advantage on saving throw
        against fireball or bane on attack rolls etc.
        """
        p_fail = 1 - get_saving_throw_success_prob(self.primary_attack.on_hit.dc, target.saving_throws[self.primary_attack.on_hit.st])
        return self.primary_attack.calculate_threat_to_target_delta(target, modifiers) + p_fail * self.secondary_attack.calculate_threat_to_target_delta(target, modifiers)



class Web(Actoid, DirectThreat):

    def __init__(self, target, factory):
        Actoid.__init__(self, actoid_flags=ActoidFlags.IS_ATTACK_LIKE | ActoidFlags.IS_DIRECT_THREAT)
        self.target = target
        self.factory = factory

    def __str__(self):
        return f"Web on {self.target}"

    def shorthand_str(self):
        return "Web"

    def get_eligible_coords(self, distances, shortest_paths):
        battle_map = Map.get()
        return battle_map.get_free_coords_in_hop_range(battle_map.get_combatant_position(self.target),
                                                       distances,
                                                       inflate_to_size=self.factory.combatant.size + self.factory.distance,
                                                       rng=battle_map.size,  # approximation, could theoretically be longer
                                                       combatant=self.factory.combatant)

    def is_current_coord_eligible(self):
        battle_map = Map.get()
        return battle_map.get_hop_distance(self.factory.combatant, self.target) >= self.factory.distance

    @map_position_toggled_cache
    def calculate_threat(self, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return self.factory.calculate_threat_to_target(self.target)

    def clear_cache(self):
        self.calculate_threat.cache_clear()
        self.calculate_threat_delta.cache_clear()

    @map_position_toggled_cache_with_key(key=lambda self, modifiers, *args, **kwargs: hashkey(tuple(modifiers.items())))
    def calculate_threat_delta(self, modifiers, *args, **kwargs):
        """
        The delta in threat when modifiers are applied on this ability.
        """
        return self.factory.calculate_threat_to_target_delta(self.target, modifiers)
