from simulator.actions.action_types import Action
from simulator.actions.actoid import FactoryFlags, Actoid, ActoidFlags
from simulator.misc import Conditions
from simulator.threat_interfaces import DirectThreatFactory, DirectThreat, RechargeFactory
from simulator.threat_utils import get_saving_throw_success_prob
import logging


logger = logging.getLogger("EncounTroll")

class WebFactory(DirectThreatFactory, RechargeFactory):

    def __init__(self, combatant, attack, recharge):
        DirectThreatFactory.__init__(self)
        self.combatant = combatant
        self.attack = attack
        self.action_type = Action.WEB
        self.flags |= FactoryFlags.IS_RANGED


    def __str__(self):
        return "WebFactory"

    def get_eligible_targets(self, battle_map):
        return [e for e in battle_map.get_enemies_without_hop_distance(self.combatant, self.distance - 1) if not e.is_affected_by(Conditions.SWALLOWED)]

    def create(self, target_combatant):
        return Web(target_combatant, self)

    def create_all(self, battle_map):
        targets = self.get_eligible_targets(battle_map)
        return [Web(t, self) for t in targets]

    def calculate_threat_to_target(self, battle_map, target, *args, **kwargs):
        """
        Calculates the threat the factory is capable of dealing to a specific target.
        This is useful for calculating threat_in from the abilities of enemies
        """
        # TODO include the threat of the PRONE in the calculation
        p_fail = 1 - get_saving_throw_success_prob(self.primary_attack.on_hit.dc, target.saving_throws[self.primary_attack.on_hit.st])
        return self.primary_attack.calculate_threat_to_target(battle_map, target) + p_fail * self.secondary_attack.calculate_threat_to_target(battle_map, target)

    def calculate_threat_to_target_delta(self, battle_map, target, modifiers, *args, **kwargs):
        """
        Calculates the threat delta of the factory to a specific target given stat modifications.
        This is useful calculating the potential reduction of threat_in caused by abilities of enemies, e.g. advantage on saving throw
        against fireball or bane on attack rolls etc.
        """
        p_fail = 1 - get_saving_throw_success_prob(self.primary_attack.on_hit.dc, target.saving_throws[self.primary_attack.on_hit.st])
        return self.primary_attack.calculate_threat_to_target_delta(battle_map, target, modifiers) + p_fail * self.secondary_attack.calculate_threat_to_target_delta(battle_map, target, modifiers)



class Web(Actoid, DirectThreat):

    def __init__(self, target_combatant, factory):
        Actoid.__init__(self, actoid_flags=ActoidFlags.IS_ATTACK_LIKE | ActoidFlags.IS_DIRECT_THREAT)
        self.target_combatant = target_combatant
        self.factory = factory

    def __str__(self):
        return f"Web on {self.target_combatant}"

    def shorthand_str(self):
        return "Web"

    def get_eligible_coords(self, battle_map, distances, shortest_paths):
        return battle_map.get_free_coords_in_hop_range(battle_map.get_combatant_position(self.target_combatant),
                                                       distances,
                                                       inflate_to_size=self.factory.combatant.size + self.factory.distance,
                                                       rng=battle_map.size,  # approximation, could theoretically be longer
                                                       combatant=self.factory.combatant)

    def is_current_coord_eligible(self, battle_map):
        return battle_map.get_hop_distance(self.factory.combatant, self.target_combatant) >= self.factory.distance

    def calculate_threat(self, battle_map, *args, **kwargs):
        """
        Threat estimation generated by the instantiated ability.
        """
        return self.factory.calculate_threat_to_target(battle_map, self.target_combatant)

    def calculate_threat_delta(self, battle_map, modifiers, *args, **kwargs):
        """
        The delta in threat when modifiers are applied on this ability.
        """
        return self.factory.calculate_threat_to_target_delta(battle_map, self.target_combatant, modifiers)